---
- name: Set hostname
  hostname:
    name: "{{ hostname_prefix }}{{ ansible_default_ipv4.address.replace('.', '-') }}"
  when:
    - ansible_os_family != "Windows"

- name: Set /etc/hosts
  template:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_os_family != "Windows"

- name: Set hostname on Windows
  win_hostname:
    name: "{{ hostname_prefix }}{{ ansible_default_ipv4.address.replace('.', '-') }}"
  register: res
  when:
    - ansible_os_family == "Windows"

- name: Set /etc/hosts on Windows
  win_template:
    src: hosts
    dest: C:\Windows\System32\drivers\etc\hosts
  when:
    - ansible_os_family == "Windows"

- name: Reboot Windows if hostname changed
  win_reboot:
  when:
    - ansible_os_family == "Windows"
    - res.reboot_required
