---
- name: Restart containerd
  service: name=containerd state=restarted enabled=yes

- name: Restart systemd-modules-load
  service: name=systemd-modules-load state=restarted enabled=yes

- name: Reload systemctl
  command: /bin/systemctl daemon-reload